import {
  Document,
  DocumentType,
  Discipline,
  RFI,
  RFIStatus,
  Priority,
  DesignIssue,
  IssueType,
  IssueStatus,
  Severity,
  Activity,
} from '../types';

// Mock Documents
const documents: Document[] = [
  {
    id: 'doc-001',
    projectId: 'project-1',
    name: 'Foundation Layout Plan.pdf',
    type: DocumentType.PDF,
    discipline: Discipline.STRUCTURAL,
    fileUrl: '/files/foundation-layout.pdf',
    fileSize: 2458624,
    version: 3,
    uploadedBy: 'user-1',
    uploadedByName: 'Sarah Johnson',
    createdAt: new Date('2025-09-15T10:00:00'),
    updatedAt: new Date('2025-09-20T14:30:00'),
  },
  {
    id: 'doc-002',
    projectId: 'project-1',
    name: 'Electrical Single Line Diagram.dwg',
    type: DocumentType.DWG,
    discipline: Discipline.MEP,
    fileUrl: '/files/electrical-sld.dwg',
    fileSize: 1567890,
    version: 2,
    uploadedBy: 'user-2',
    uploadedByName: 'Mike Chen',
    createdAt: new Date('2025-09-16T09:15:00'),
    updatedAt: new Date('2025-09-19T11:45:00'),
  },
  {
    id: 'doc-003',
    projectId: 'project-1',
    name: 'Architectural Floor Plan - Level 1.pdf',
    type: DocumentType.PDF,
    discipline: Discipline.ARCHITECTURAL,
    fileUrl: '/files/floor-plan-l1.pdf',
    fileSize: 3789456,
    version: 5,
    uploadedBy: 'user-3',
    uploadedByName: 'Emily Davis',
    createdAt: new Date('2025-09-10T08:00:00'),
    updatedAt: new Date('2025-09-21T09:00:00'),
  },
  {
    id: 'doc-004',
    projectId: 'project-1',
    name: 'Site Grading Plan.dxf',
    type: DocumentType.DXF,
    discipline: Discipline.CIVIL,
    fileUrl: '/files/site-grading.dxf',
    fileSize: 987654,
    version: 1,
    uploadedBy: 'user-4',
    uploadedByName: 'David Wilson',
    createdAt: new Date('2025-09-18T13:30:00'),
    updatedAt: new Date('2025-09-18T13:30:00'),
  },
  {
    id: 'doc-005',
    projectId: 'project-1',
    name: 'Landscape Master Plan.pdf',
    type: DocumentType.PDF,
    discipline: Discipline.LANDSCAPE,
    fileUrl: '/files/landscape-plan.pdf',
    fileSize: 4567890,
    version: 2,
    uploadedBy: 'user-5',
    uploadedByName: 'Lisa Anderson',
    createdAt: new Date('2025-09-17T10:20:00'),
    updatedAt: new Date('2025-09-20T16:15:00'),
  },
];

// Mock RFIs
const rfis: RFI[] = [
  {
    id: 'rfi-001',
    projectId: 'project-1',
    rfiNumber: 'RFI-2025-001',
    title: 'Foundation Rebar Spacing Clarification',
    description: 'Need clarification on the rebar spacing for the foundation in grid lines A-C/1-3. The structural drawing shows 12" spacing but the specification calls for 10" spacing.',
    status: RFIStatus.OPEN,
    priority: Priority.HIGH,
    createdBy: 'user-1',
    createdByName: 'Sarah Johnson',
    assignedTo: 'user-6',
    assignedToName: 'Robert Brown (Structural Engineer)',
    dueDate: new Date('2025-09-25T17:00:00'),
    createdAt: new Date('2025-09-20T10:00:00'),
    updatedAt: new Date('2025-09-20T10:00:00'),
  },
  {
    id: 'rfi-002',
    projectId: 'project-1',
    rfiNumber: 'RFI-2025-002',
    title: 'HVAC Duct Routing Conflict',
    description: 'There is a conflict between the HVAC ducts and electrical cable trays in the ceiling of Level 2. Please provide revised routing.',
    status: RFIStatus.IN_REVIEW,
    priority: Priority.CRITICAL,
    createdBy: 'user-2',
    createdByName: 'Mike Chen',
    assignedTo: 'user-7',
    assignedToName: 'Jennifer Lee (MEP Coordinator)',
    dueDate: new Date('2025-09-23T17:00:00'),
    createdAt: new Date('2025-09-19T14:30:00'),
    updatedAt: new Date('2025-09-20T09:15:00'),
  },
  {
    id: 'rfi-003',
    projectId: 'project-1',
    rfiNumber: 'RFI-2025-003',
    title: 'Window Type Specification',
    description: 'The architectural drawings show window type W-3 on the north elevation, but this type is not included in the window schedule. Please clarify.',
    status: RFIStatus.RESPONDED,
    priority: Priority.MEDIUM,
    createdBy: 'user-3',
    createdByName: 'Emily Davis',
    assignedTo: 'user-8',
    assignedToName: 'Tom Garcia (Architect)',
    dueDate: new Date('2025-09-22T17:00:00'),
    respondedAt: new Date('2025-09-21T11:30:00'),
    response: 'Window type W-3 should be W-2A as per the updated schedule. Please refer to the revised window schedule document uploaded today.',
    createdAt: new Date('2025-09-18T11:00:00'),
    updatedAt: new Date('2025-09-21T11:30:00'),
  },
  {
    id: 'rfi-004',
    projectId: 'project-1',
    rfiNumber: 'RFI-2025-004',
    title: 'Fire Sprinkler Head Coverage',
    description: 'The fire protection drawing shows insufficient sprinkler coverage in the storage room B-101. Please review and provide additional sprinkler locations if needed.',
    status: RFIStatus.CLOSED,
    priority: Priority.HIGH,
    createdBy: 'user-4',
    createdByName: 'David Wilson',
    assignedTo: 'user-9',
    assignedToName: 'Maria Rodriguez (Fire Protection Engineer)',
    dueDate: new Date('2025-09-20T17:00:00'),
    respondedAt: new Date('2025-09-19T15:45:00'),
    response: 'Additional sprinkler heads have been added to the design. See revised fire protection drawing FP-101 Rev 2.',
    createdAt: new Date('2025-09-17T09:30:00'),
    updatedAt: new Date('2025-09-20T08:00:00'),
  },
  {
    id: 'rfi-005',
    projectId: 'project-1',
    rfiNumber: 'RFI-2025-005',
    title: 'Waterproofing Detail at Foundation Wall',
    description: 'Please provide waterproofing detail for the foundation wall penetration at grid line D-5.',
    status: RFIStatus.OPEN,
    priority: Priority.MEDIUM,
    createdBy: 'user-5',
    createdByName: 'Lisa Anderson',
    assignedTo: 'user-6',
    assignedToName: 'Robert Brown (Structural Engineer)',
    dueDate: new Date('2025-09-26T17:00:00'),
    createdAt: new Date('2025-09-21T08:30:00'),
    updatedAt: new Date('2025-09-21T08:30:00'),
  },
];

// Mock Design Issues
const issues: DesignIssue[] = [
  {
    id: 'issue-001',
    projectId: 'project-1',
    issueNumber: 'ISS-2025-001',
    title: 'Structural Beam Conflicts with HVAC Duct',
    description: 'The structural beam at grid line E-3 conflicts with the main HVAC supply duct. The duct needs to be rerouted or the beam needs modification.',
    type: IssueType.CONFLICT,
    severity: Severity.CRITICAL,
    status: IssueStatus.OPEN,
    costImpact: 15000,
    scheduleImpact: 5,
    assignedTo: 'user-6',
    assignedToName: 'Robert Brown',
    createdAt: new Date('2025-09-19T10:00:00'),
    updatedAt: new Date('2025-09-20T14:00:00'),
  },
  {
    id: 'issue-002',
    projectId: 'project-1',
    issueNumber: 'ISS-2025-002',
    title: 'Missing Electrical Panel Schedule',
    description: 'The electrical panel schedule for Panel EP-2B is missing from the electrical drawings package.',
    type: IssueType.MISSING_INFO,
    severity: Severity.HIGH,
    status: IssueStatus.IN_PROGRESS,
    costImpact: 0,
    scheduleImpact: 2,
    assignedTo: 'user-2',
    assignedToName: 'Mike Chen',
    createdAt: new Date('2025-09-18T13:45:00'),
    updatedAt: new Date('2025-09-20T10:30:00'),
  },
  {
    id: 'issue-003',
    projectId: 'project-1',
    issueNumber: 'ISS-2025-003',
    title: 'Door Schedule Discrepancy',
    description: 'Door types D-3 and D-4 have conflicting dimensions between the door schedule and floor plans.',
    type: IssueType.ERROR,
    severity: Severity.MEDIUM,
    status: IssueStatus.RESOLVED,
    costImpact: 3500,
    scheduleImpact: 1,
    assignedTo: 'user-8',
    assignedToName: 'Tom Garcia',
    resolvedAt: new Date('2025-09-20T16:00:00'),
    resolution: 'Door schedule has been updated to match floor plan dimensions. All affected doors have been verified.',
    createdAt: new Date('2025-09-16T11:30:00'),
    updatedAt: new Date('2025-09-20T16:00:00'),
  },
  {
    id: 'issue-004',
    projectId: 'project-1',
    issueNumber: 'ISS-2025-004',
    title: 'Ceiling Height Clarification Needed',
    description: 'The reflected ceiling plan shows 9\'-0" ceiling height, but architectural sections show 9\'-6". Need clarification for MEP coordination.',
    type: IssueType.CLARIFICATION,
    severity: Severity.MEDIUM,
    status: IssueStatus.OPEN,
    costImpact: 0,
    scheduleImpact: 0,
    assignedTo: 'user-3',
    assignedToName: 'Emily Davis',
    createdAt: new Date('2025-09-21T09:00:00'),
    updatedAt: new Date('2025-09-21T09:00:00'),
  },
  {
    id: 'issue-005',
    projectId: 'project-1',
    issueNumber: 'ISS-2025-005',
    title: 'Plumbing Riser Diagram Error',
    description: 'The plumbing riser diagram shows incorrect pipe sizes for the domestic water supply to Level 3.',
    type: IssueType.ERROR,
    severity: Severity.HIGH,
    status: IssueStatus.IN_PROGRESS,
    costImpact: 8000,
    scheduleImpact: 3,
    assignedTo: 'user-7',
    assignedToName: 'Jennifer Lee',
    createdAt: new Date('2025-09-20T15:20:00'),
    updatedAt: new Date('2025-09-21T08:45:00'),
  },
];

// Mock Activities
const activities: Activity[] = [
  {
    id: 'activity-001',
    type: 'document_upload',
    title: 'New Document Uploaded',
    description: 'Sarah Johnson uploaded "Foundation Layout Plan.pdf" (Rev 3)',
    userId: 'user-1',
    userName: 'Sarah Johnson',
    timestamp: new Date('2025-09-21T10:00:00'),
  },
  {
    id: 'activity-002',
    type: 'rfi_created',
    title: 'RFI Created',
    description: 'Lisa Anderson created RFI-2025-005: Waterproofing Detail at Foundation Wall',
    userId: 'user-5',
    userName: 'Lisa Anderson',
    timestamp: new Date('2025-09-21T08:30:00'),
  },
  {
    id: 'activity-003',
    type: 'rfi_responded',
    title: 'RFI Responded',
    description: 'Tom Garcia responded to RFI-2025-003: Window Type Specification',
    userId: 'user-8',
    userName: 'Tom Garcia',
    timestamp: new Date('2025-09-21T11:30:00'),
  },
  {
    id: 'activity-004',
    type: 'issue_resolved',
    title: 'Issue Resolved',
    description: 'Tom Garcia resolved ISS-2025-003: Door Schedule Discrepancy',
    userId: 'user-8',
    userName: 'Tom Garcia',
    timestamp: new Date('2025-09-20T16:00:00'),
  },
  {
    id: 'activity-005',
    type: 'issue_created',
    title: 'Issue Created',
    description: 'Emily Davis created ISS-2025-004: Ceiling Height Clarification Needed',
    userId: 'user-3',
    userName: 'Emily Davis',
    timestamp: new Date('2025-09-21T09:00:00'),
  },
];

export const mockData = {
  documents,
  rfis,
  issues,
  activities,
};